import { ExecutionRun } from "@composableai/studio-common";
import { UploadContentObjectPayload } from "@composableai/zeno-client";
import { ContentObjectStatus, ContentObjectType, DSLActivityExecutionPayload, DSLActivitySpec } from "@composableai/zeno-common";
import { log } from "@temporalio/activity";
import { setupActivity } from "../../dsl/setup/ActivityContext.js";
import { ActivityParamNotFound } from "../../errors.js";



interface CreateOrUpdateDocumentFromInteractionRunParams {
    /**
     * The execution run object to use. Required.
     * Not required in params since it is usually fetched
     */
    run?: ExecutionRun,
    /**
     * The document type to use. Required if updateExistingId is false.
     * Not required in params since it is usually fetched
     */
    docType?: ContentObjectType,

    updateExistingId?: string,
    fallbackName?: string, // a name to use if no one was generated by the interaction
}

export interface CreateOrUpdateDocumentFromInteractionRun extends DSLActivitySpec<CreateOrUpdateDocumentFromInteractionRunParams> {
    name: 'createOrUpdateDocumentFromInteractionRun';
}

export async function createOrUpdateDocumentFromInteractionRun(payload: DSLActivityExecutionPayload) {

    const { params, zeno } = await setupActivity<CreateOrUpdateDocumentFromInteractionRunParams>(payload);

    const run = params.run!;
    const docType = params.docType!;

    if (!run) {
        throw new ActivityParamNotFound("run", payload.activity);
    }
    if (!docType && !params.updateExistingId) {
        throw new ActivityParamNotFound("docType", payload.activity);
    }


    log.info("Creating document from interaction result", { runId: run.id, docType: docType?.name });

    const result = run.result;
    const resultIsObject = typeof result === 'object';
    const inputData = run.parameters;
    const parent = payload.objectIds.length > 1 ? undefined : payload.objectIds[0];

    let name: string;
    if (resultIsObject) {
        name = result['name'] || result["title"] || inputData['name'] || params.fallbackName || 'Untitled';
    } else {
        name = inputData['name'] || params.fallbackName || 'Untitled';
    }

    const docPayload: UploadContentObjectPayload = {
        name,
        parent: parent,
        properties: resultIsObject ? result : {},
        text: !resultIsObject ? result : undefined,
        type: docType?.id,
        status: ContentObjectStatus.completed,
    };
    log.info("Creating document with payload", docPayload);

    //create or update the document
    let newDoc: boolean = false;
    let doc = undefined;
    if (params.updateExistingId) {
        doc = await zeno.objects.update(params.updateExistingId, docPayload);
    } else {
        doc = await zeno.objects.create(docPayload);
        newDoc = true;
    }

    log.info(`Document ${docType.name + ' '}${doc.id}(${doc.name}) ${newDoc ? 'created' : 'updated'}`);
    return { id: doc.id, isNew: newDoc, type: docType.name }
}