name: composable
on:
  - push
jobs:
  composableai-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
      - run: |
          pnpm install
      - run: |
          pnpm -r build
      - name: Run tests
        run: |
          pnpm \
            --filter '!./packages/api-fetch-client' \
            --filter '!./packages/blobs' \
            --filter '!./packages/converters' \
            --filter '!./packages/common' \
            --filter '!./packages/workflow' \
            -r test

  api-fetch-client-test:
    runs-on: ubuntu-latest
    needs: composableai-build
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
      - run: pnpm install
      - run: npm --prefix packages/api-fetch-client test

  converters-test:
    runs-on: ubuntu-latest
    needs: composableai-build
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
      - name: Install pandoc
        uses: pandoc/actions/setup@main
      - run: pnpm install
      - run: npm --prefix packages/converters test
